server:
  port: 8080
  servlet:
    context-path: /pharma-registry

spring:
  application:
    name: pharmaceutical-registry

  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/pharma_registry
    username: postgres
    password: admin123  # Use the password you set during installation
    driver-class-name: org.postgresql.Driver

  # JPA Configuration for PostgreSQL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# Logging Configuration
logging:
  level:
    com.pharma.registry: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html